### ISSUE TITLE
logging invocation with null arguments fail

### ISSUE THREAD

**Issue by maciejmikosik** [maciejmikosik/logbuddy#4]
```
Logger console = console(new TextRenderer(), new OutputStreamWriter(System.out));
Decorator decorator = logging(console);
Object object = decorator.decorate(new Object());
object.equals(null);
```

throws exception

```
Exception in thread "main" org.logbuddy.LogBuddyException
    at org.logbuddy.LogBuddyException.check(LogBuddyException.java:24)
    at org.logbuddy.model.Invocation.invocation(Invocation.java:29)
    at org.logbuddy.decorator.LoggingDecorator$DecorateHandler.handle(LoggingDecorator.java:61)
    at net.bytebuddy.renamed.java.lang.Object$ByteBuddy$4n9B57KI.equals(Unknown Source)
    at Bug.main(Bug.java:17)
```

**Comment by maciejmikosik** [comment]
fixed logging of invocation with null arguments 1f8c83ca7df9ba2489d3e089ff1c217b20b66f38
